# Learn Keras for Deep Neural Networks
## An Introduction to Deep Learning and Keras


A sneak peek in the Keras Framework

In [17]:
#Import required packages
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

In [18]:
# Getting the data ready
# Generate train dummy data for 1000 Students and dummy test for 500
#Columns :Age, Hours of Study & Avg Previous test scores
np.random.seed(2018)
train_data, test_data = np.random.random((1000, 3)), np.random.random((500, 3))
#Generate dummy results for 1000 students : Whether Passed (1) or Failed (0)
labels = np.random.randint(2, size=(1000, 1))

In [19]:
train_data

array([[0.88234931, 0.10432774, 0.90700933],
       [0.3063989 , 0.44640887, 0.58998539],
       [0.8371111 , 0.69780061, 0.80280284],
       ...,
       [0.76474832, 0.12224649, 0.06019634],
       [0.21847107, 0.57064847, 0.27701246],
       [0.97785211, 0.81210972, 0.34780075]])

In [20]:
test_data

array([[0.35981783, 0.64707122, 0.16858627],
       [0.95089881, 0.24401454, 0.39478811],
       [0.99185888, 0.01995682, 0.19105642],
       ...,
       [0.03335012, 0.35559007, 0.5386409 ],
       [0.3804594 , 0.11970055, 0.08783101],
       [0.83887832, 0.26936355, 0.90847875]])

In [21]:
#Defining the model structure with the required layers, # of neurons, activation function and optimizers
model = Sequential()
model.add(Dense(5, input_dim=3, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [22]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (None, 5)                 20        
                                                                 
 dense_19 (Dense)            (None, 4)                 24        
                                                                 
 dense_20 (Dense)            (None, 1)                 5         
                                                                 
Total params: 49
Trainable params: 49
Non-trainable params: 0
_________________________________________________________________


In [23]:
#Train the model and make predictions
model.fit(train_data, labels, epochs=10, batch_size=32)

Epoch 1/10
32/32 [==============================] - 2s 6ms/step - loss: 0.6965 - accuracy: 0.4970
Epoch 2/10
32/32 [==============================] - 0s 5ms/step - loss: 0.6952 - accuracy: 0.5020
Epoch 3/10
32/32 [==============================] - 0s 5ms/step - loss: 0.6945 - accuracy: 0.5120
Epoch 4/10
32/32 [==============================] - 0s 5ms/step - loss: 0.6943 - accuracy: 0.4910
Epoch 5/10
32/32 [==============================] - 0s 5ms/step - loss: 0.6939 - accuracy: 0.4960
Epoch 6/10
32/32 [==============================] - 0s 5ms/step - loss: 0.6938 - accuracy: 0.4860
Epoch 7/10
32/32 [==============================] - 0s 5ms/step - loss: 0.6936 - accuracy: 0.4850
Epoch 8/10
32/32 [==============================] - 0s 5ms/step - loss: 0.6935 - accuracy: 0.4930
Epoch 9/10
32/32 [==============================] - 0s 6ms/step - loss: 0.6934 - accuracy: 0.4930
Epoch 10/10
32/32 [==============================] - 0s 5ms/step - loss: 0.6933 - accuracy: 0.4930


In [24]:
#Make predictions from the trained model
predictions = model.predict(test_data)

16/16 [==============================] - 0s 3ms/step


In [25]:
predictions

array([[0.49504074],
       [0.4859416 ],
       [0.4859416 ],
       [0.4884657 ],
       [0.5078338 ],
       [0.49037918],
       [0.4859416 ],
       [0.4859416 ],
       [0.4962441 ],
       [0.48787293],
       [0.49300972],
       [0.500146  ],
       [0.4934273 ],
       [0.5087889 ],
       [0.4859416 ],
       [0.50126404],
       [0.49425742],
       [0.50215757],
       [0.50161123],
       [0.4999982 ],
       [0.48866633],
       [0.5177535 ],
       [0.48628438],
       [0.49882916],
       [0.4859416 ],
       [0.48913574],
       [0.5073065 ],
       [0.4987795 ],
       [0.4917665 ],
       [0.5119133 ],
       [0.4884134 ],
       [0.50185037],
       [0.50270295],
       [0.49295235],
       [0.5048602 ],
       [0.48788613],
       [0.49700415],
       [0.5052407 ],
       [0.4859416 ],
       [0.4859416 ],
       [0.5132614 ],
       [0.5084756 ],
       [0.5110027 ],
       [0.50020885],
       [0.50708026],
       [0.48857826],
       [0.4859416 ],
       [0.485

In [26]:
#Import required packages
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

# Getting the data ready
# Generate train dummy data for 1000 Students and dummy test for 500
#Columns :Age, Hours of Study & Avg Previous test scores
np.random.seed(2018)
train_data, test_data = np.random.random((1000, 3)), np.random.random((500, 3))
#Generate dummy results for 1000 students : Whether Passed (1) or Failed (0)
labels = np.random.randint(2, size=(1000, 1))

#Defining the model structure with the required layers, # of neurons, activation function and optimizers
model = Sequential()
model.add(Dense(5, input_dim=3, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

#Train the model and make predictions
model.fit(train_data, labels, epochs=10, batch_size=32)

#Make predictions from the trained model
predictions = model.predict(test_data)


Epoch 1/10
32/32 [==============================] - 1s 4ms/step - loss: 0.7045 - accuracy: 0.4930
Epoch 2/10
32/32 [==============================] - 0s 5ms/step - loss: 0.6987 - accuracy: 0.4960
Epoch 3/10
32/32 [==============================] - 0s 4ms/step - loss: 0.6962 - accuracy: 0.5020
Epoch 4/10
32/32 [==============================] - 0s 5ms/step - loss: 0.6948 - accuracy: 0.5060
Epoch 5/10
32/32 [==============================] - 0s 4ms/step - loss: 0.6939 - accuracy: 0.5110
Epoch 6/10
32/32 [==============================] - 0s 5ms/step - loss: 0.6935 - accuracy: 0.5140
Epoch 7/10
32/32 [==============================] - 0s 5ms/step - loss: 0.6931 - accuracy: 0.5140
Epoch 8/10
32/32 [==============================] - 0s 5ms/step - loss: 0.6929 - accuracy: 0.4940
Epoch 9/10
32/32 [==============================] - 0s 5ms/step - loss: 0.6929 - accuracy: 0.4930
Epoch 10/10
16/16 [==============================] - 0s 3ms/step


In [27]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation

np.random.seed(2018)

# Generate dummy training dataset
x_train = np.random.random((6000,10))
y_train = np.random.randint(2, size=(6000, 1))

# Generate dummy validation dataset
x_val = np.random.random((2000,10))
y_val = np.random.randint(2, size=(2000, 1))

# Generate dummy test dataset
x_test = np.random.random((2000,10))
y_test = np.random.randint(2, size=(2000, 1))

#Define the model architecture
model = Sequential()
model.add(Dense(64, input_dim=10,activation = "relu")) #Layer 1
model.add(Dense(32,activation = "relu"))               #Layer 2
model.add(Dense(16,activation = "relu"))               #Layer 3
model.add(Dense(8,activation = "relu"))                #Layer 4
model.add(Dense(4,activation = "relu"))                #Layer 5
model.add(Dense(1,activation = "sigmoid"))             #Output Layer

#Configure the model
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

#Train the model
model.fit(x_train, y_train, batch_size=64, epochs=10, validation_data=(x_val,y_val))

Epoch 1/10
94/94 [==============================] - 2s 10ms/step - loss: 0.6932 - accuracy: 0.5030 - val_loss: 0.6930 - val_accuracy: 0.5060
Epoch 2/10
94/94 [==============================] - 1s 7ms/step - loss: 0.6932 - accuracy: 0.5032 - val_loss: 0.6931 - val_accuracy: 0.5135
Epoch 3/10
94/94 [==============================] - 1s 8ms/step - loss: 0.6931 - accuracy: 0.5072 - val_loss: 0.6930 - val_accuracy: 0.5045
Epoch 4/10
94/94 [==============================] - 1s 6ms/step - loss: 0.6931 - accuracy: 0.5088 - val_loss: 0.6930 - val_accuracy: 0.5045
Epoch 5/10
94/94 [==============================] - 0s 4ms/step - loss: 0.6931 - accuracy: 0.5067 - val_loss: 0.6931 - val_accuracy: 0.5045
Epoch 6/10
94/94 [==============================] - 0s 5ms/step - loss: 0.6930 - accuracy: 0.5110 - val_loss: 0.6930 - val_accuracy: 0.5085
Epoch 7/10
94/94 [==============================] - 1s 8ms/step - loss: 0.6926 - accuracy: 0.5157 - val_loss: 0.6930 - val_accuracy: 0.5060
Epoch 8/10
94/94 [=

In [28]:
#Make predictions from the trained model
predictions = model.predict(x_test)

63/63 [==============================] - 0s 2ms/step
