# 20220822 | Creating a Perceptron Manually
> For the OR-Gate Problem

In [1]:
import numpy as np

## Perceptron
### The parts

In [2]:
X = np.array([1, 0, 0])
W = np.array([1, 1, 1])

In [3]:
def unit_activation(n):
   return 1 if n > 0 else 0

In [4]:
out = W.T * X
print(out)
ans = print(unit_activation(np.sum(out)))

[1 0 0]
1


In [5]:
if ans == X[1] or X[2]:
    print('correct')
else:
    print('wrong')

wrong


### Combining the parts

In [10]:
x0 = -1

thresh = -1
w0 = -thresh
w1 = 1
w2 = 1
W = np.array([w0, w1, w2])

num_iter = 2
learning_rate = 1

print("Perceptron\n===")
print("      X       |      W      |  sum  | pred | real | isCorrect")
for i in range(num_iter):
    for x1 in [0, 1]:
        for x2 in [0, 1]:
            X = np.array([x0, x1, x2])
            sum = np.sum(W.T * X)
            pred = unit_activation(sum)
            
            y = x1 or x2

            print(f"{X} |   {W}   |    {sum}    |    {pred}    |    {x1 or x2}   |    {bool(y == pred)}")
            
            # correcting the weights:
            if y != pred:
                dW = learning_rate * (y - pred) * X[1:]
                print(dW)
                W[1:] += dW


Perceptron
===
      X       |      W      |  sum  | pred | real | isCorrect
[-1  0  0] |   [1 1 1]   |    -1    |    0    |    0   |    True
[-1  0  1] |   [1 1 1]   |    0    |    0    |    1   |    False
[0 1]
[-1  1  0] |   [1 1 2]   |    0    |    0    |    1   |    False
[1 0]
[-1  1  1] |   [1 2 2]   |    3    |    1    |    1   |    True
[-1  0  0] |   [1 2 2]   |    -1    |    0    |    0   |    True
[-1  0  1] |   [1 2 2]   |    1    |    1    |    1   |    True
[-1  1  0] |   [1 2 2]   |    1    |    1    |    1   |    True
[-1  1  1] |   [1 2 2]   |    3    |    1    |    1   |    True


## Adaline

In [ ]:
x0 = -1

thresh = -1
w0 = -thresh
w1 = 1
w2 = 1
W = np.array([w0, w1, w2], dtype='float')

num_iter = 100
learning_rate = 1

print("Adaline\n===")
# print("      X       |      W      |  sum  | pred | real | isCorrect")
for i in range(num_iter):
    print(f"iter: {i}")
    y_all = np.zeros(4, dtype='float')
    pred_all = np.zeros(4, dtype='float')
    for x1 in [0, 1]:
        for x2 in [0, 1]:
            X = np.array([x0, x1, x2])
            sum = np.sum(W.T * X)
            pred = unit_activation(sum)
            y = x1 or x2

            # print(f"{X} |   {W}   |    {sum}    |    {pred}    |    {x1 or x2}   |    {bool(y == pred)}")

            y_all[ x1 * 2 + x2] = y
            pred_all[x1 * 2 + x2] = sum

    print(f"Y: {y_all}")
    print(f"P(after activation): {pred_all}")

    if not (y_all == pred_all).all():
        # dW = learning_rate * (y_all - pred_all) * X
        # print(dW)
        cost = np.sum(np.square(y_all - pred_all))
        print(f"cost: {cost}")
        print(f"W: {W}\n")
        dW = 0.1
        if cost < 0:
            W += dW
        else:
            W -= dW


Adaline
===
iter: 0
Y: [0. 1. 1. 1.]
P(after activation): [-1.  0.  0.  1.]
cost: 3.0
W: [1. 1. 1.]

iter: 1
Y: [0. 1. 1. 1.]
P(after activation): [-0.9  0.   0.   0.9]
cost: 2.82
W: [0.9 0.9 0.9]

iter: 2
Y: [0. 1. 1. 1.]
P(after activation): [-0.8  0.   0.   0.8]
cost: 2.68
W: [0.8 0.8 0.8]

iter: 3
Y: [0. 1. 1. 1.]
P(after activation): [-0.7  0.   0.   0.7]
cost: 2.58
W: [0.7 0.7 0.7]

iter: 4
Y: [0. 1. 1. 1.]
P(after activation): [-0.6  0.   0.   0.6]
cost: 2.5200000000000005
W: [0.6 0.6 0.6]

iter: 5
Y: [0. 1. 1. 1.]
P(after activation): [-0.5  0.   0.   0.5]
cost: 2.5
W: [0.5 0.5 0.5]

iter: 6
Y: [0. 1. 1. 1.]
P(after activation): [-0.4  0.   0.   0.4]
cost: 2.52
W: [0.4 0.4 0.4]

iter: 7
Y: [0. 1. 1. 1.]
P(after activation): [-0.3  0.   0.   0.3]
cost: 2.5799999999999996
W: [0.3 0.3 0.3]

iter: 8
Y: [0. 1. 1. 1.]
P(after activation): [-0.2  0.   0.   0.2]
cost: 2.6799999999999997
W: [0.2 0.2 0.2]

iter: 9
Y: [0. 1. 1. 1.]
P(after activation): [-0.1  0.   0.   0.1]
cost: 2.819999