In [2]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

## Loading the `iris` Dataset

In [20]:
from sklearn import datasets

iris = datasets.load_iris()
iris_df = pd.concat([
    pd.DataFrame(iris.data),
    pd.DataFrame(iris.target)
], axis=1)
iris_df.columns = [
    'sepal_len',
    'sepal_wid',
    'petal_len',
    'petal_wid',
    'Label'
]

In [21]:
iris_df.describe()

sepal_len   sepal_wid   petal_len   petal_wid       Label
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333    1.000000
std      0.828066    0.435866    1.765298    0.762238    0.819232
min      4.300000    2.000000    1.000000    0.100000    0.000000
25%      5.100000    2.800000    1.600000    0.300000    0.000000
50%      5.800000    3.000000    4.350000    1.300000    1.000000
75%      6.400000    3.300000    5.100000    1.800000    2.000000
max      7.900000    4.400000    6.900000    2.500000    2.000000

## Loading the `CICIDS` Dataset

In [25]:
cicids_df = pd.read_csv("../test_MachineLearningCVE.csv", skipinitialspace=True)

In [26]:
cicids_df.describe()

Destination Port  Flow Duration  Total Fwd Packets  \
count     566149.000000   5.661490e+05      566149.000000   
mean        8023.536525   1.475572e+07           7.433398   
std        18237.981102   3.361749e+07         438.398407   
min            0.000000   0.000000e+00           1.000000   
25%           53.000000   1.550000e+02           2.000000   
50%           80.000000   3.131600e+04           2.000000   
75%          443.000000   3.175237e+06           5.000000   
max        65533.000000   1.200000e+08      199057.000000   

       Total Backward Packets  Total Length of Fwd Packets  \
count           566149.000000                 5.661490e+05   
mean                 7.845504                 5.480510e+02   
std                583.054409                 7.455954e+03   
min                  0.000000                 0.000000e+00   
25%                  1.000000                 1.200000e+01   
50%                  2.000000                 6.200000e+01   
75%                  4.000000                 1.870000e+02   
max             269619.000000                 2.866110e+06   

       Total Length of Bwd Packets  Fwd Packet Length Max  \
count                 5.661490e+05          566149.000000   
mean                  1.025244e+04             206.930559   
std                   1.277379e+06             711.715142   
min                   0.000000e+00               0.000000   
25%                   2.000000e+00               6.000000   
50%                   1.240000e+02              37.000000   
75%                   4.800000e+02              81.000000   
max                   5.840000e+08           24820.000000   

       Fwd Packet Length Min  Fwd Packet Length Mean  Fwd Packet Length Std  \
count          566149.000000           566149.000000          566149.000000   
mean               18.798663               58.104949              68.552052   
std                60.642342              184.868811             277.965989   
min                 0.000000                0.000000               0.000000   
25%                 0.000000                6.000000               0.000000   
50%                 2.000000               34.000000               0.000000   
75%                36.000000               50.000000              26.162951   
max              1983.000000             4638.923469            7125.596846   

       ...  min_seg_size_forward   Active Mean    Active Std    Active Max  \
count  ...         566149.000000  5.661490e+05  5.661490e+05  5.661490e+05   
mean   ...             26.122669  8.265636e+04  4.124628e+04  1.546799e+05   
std    ...              6.579084  7.072071e+05  4.035803e+05  1.069064e+06   
min    ...              0.000000  0.000000e+00  0.000000e+00  0.000000e+00   
25%    ...             20.000000  0.000000e+00  0.000000e+00  0.000000e+00   
50%    ...             24.000000  0.000000e+00  0.000000e+00  0.000000e+00   
75%    ...             32.000000  0.000000e+00  0.000000e+00  0.000000e+00   
max    ...            126.000000  1.070000e+08  6.390000e+07  1.070000e+08   

         Active Min     Idle Mean      Idle Std      Idle Max      Idle Min  \
count  5.661490e+05  5.661490e+05  5.661490e+05  5.661490e+05  5.661490e+05   
mean   5.951514e+04  8.290722e+06  4.991163e+05  8.667073e+06  7.897870e+06   
std    6.407873e+05  2.359744e+07  4.572702e+06  2.432631e+07  2.333391e+07   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
75%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
max    1.070000e+08  1.200000e+08  7.514502e+07  1.200000e+08  1.200000e+08   

               Label  
count  566149.000000  
mean        1.064391  
std         2.576357  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max        14.000000  

[8 rows x 79 

## Preprocessing Both Datasets

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer, MinMaxScaler

def split_normalize_scale(df, train_size):
    df_train, df_test = train_test_split(df, train_size=0.7, random_state=1)

    data_train = df_train.iloc[:, 0:-2].to_numpy()
    data_test = df_test.iloc[:, 0:-2].to_numpy()

    norm = Normalizer()
    norm.fit(data_train)
    data_train = norm.transform(data_train)
    data_test = norm.transform(data_test)

    scaler = MinMaxScaler()
    scaler.fit(data_train)
    data_train = scaler.transform(data_train)
    data_test = scaler.transform(data_test)

    labels_train = df_train.iloc[:, -1].to_numpy()
    labels_test = df_test.iloc[:, -1].to_numpy()

    print(f"training data shape: {data_train.shape}")
    print(f"training labels shape: {labels_train.shape}")

    print(f"testing data shape: {data_test.shape}")
    print(f"testing labels shape: {labels_test.shape}")

    return data_train, labels_train, data_test, labels_test

In [41]:
X_train_cicids, y_train_cicids, X_test_cicids, y_test_cicids = split_normalize_scale(cicids_df, train_size=0.7)

training data shape: (396304, 77)
training labels shape: (396304,)
testing data shape: (169845, 77)
testing labels shape: (169845,)


In [37]:
X_train_iris, y_train_iris, X_test_iris, y_test_iris = split_normalize_scale(iris_df, train_size=0.7)

training data shape: (105, 3)
training labels shape: (105,)
testing data shape: (45, 3)
testing labels shape: (45,)


## Plotting Shit

## Supervised Learning

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

### Perceptron

### Adaline/Normal Regression

### Logistic Regression

In [38]:
from sklearn.linear_model import LogisticRegression

def lr(X_train, y_train, X_test, y_test):
    lr = LogisticRegression(random_state=1)
    lr.fit(X_train, y_train)
    preds = lr.predict(X_test)
    print(classification_report(y_test, preds))
    print(confusion_matrix(y_test, preds))

In [42]:
lr(X_train_cicids, y_train_cicids, X_test_cicids, y_test_cicids)

/home/sam/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/sam/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.97      0.97      0.97    136225
           1       0.00      0.00      0.00       136
           2       0.84      0.91      0.87      7715
           3       0.89      0.71      0.79       642
           4       0.84      0.90      0.87     13824
           5       0.00      0.00      0.00       320
           6       0.93      0.29      0.44       373
           7       0.81      0.77      0.79       465
          10       0.86      0.90      0.88      9649
          11       0.00      0.00      0.00       352
          12       0.00      0.00      0.00       104
          13       0.00      0.00      0.00         2
          14       0.00      0.00      0.00        38

    accuracy                           0.95    169845
   macro avg       0.47      0.42      0.43    169845
weighted avg       0.94      0.95      0.95    169845

[[131989      6    616     53   2068     23      0     60   1410      0
       

/home/sam/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/sam/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [39]:
lr(X_train_iris, y_train_iris, X_test_iris, y_test_iris)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.91      0.56      0.69        18
           2       0.60      0.92      0.73        13

    accuracy                           0.80        45
   macro avg       0.84      0.83      0.81        45
weighted avg       0.85      0.80      0.80        45

[[14  0  0]
 [ 0 10  8]
 [ 0  1 12]]


### Decision Tree

### Naïve Bayes

### K-NN

### Deep Learning

## Unsupervised Learning

### K-Means Clustering

### Heirarchical Clustering